<?php
    $_helper = $this->helper('ddv\CustomMenu\Helper\Data');
    $_config = $_helper->getConfig('custommenu');
    $columnsLimit = 0;
    if($_config['general']['enable']) {
?>
<?php $_menu = $block->getCustomMenuHtml(); ?>

<nav class="navigation custommenu main-nav main-nav4">
    <ul>
        <?php echo $_menu; ?>
    </ul>
</nav>

<script type="text/javascript">
    require([
        'jquery',
        'ddv/custommenu'
    ], function ($) {
        $(".custommenu").CustomMenu();
    });
</script>
<?php
    } else {
?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit); ?>

<nav class="navigation custommenu main-nav">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?php /* @escapeNotVerified */ echo $_menu; ?>
    </ul>
</nav>

<?php
    }
?>