<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
if($banners = $block->getBannerCollection()):
	$slider = $block->getSlider();
	$sliderId = $block->getSliderId(); 
?>
<div class="banner-home4 simple-owl-slider">
	<div class="slider_<?php echo $sliderId; ?> wrap-item">
		<?php foreach($banners as $banner){	?>
			<div class="item-banner4">
			<?php
			$link = '#';
			if($banner->getSlideLink()){
				$link = $banner->getSlideLink();
			}
				$html = '<div class="banner-thumb">
							<a href="'. $link .'"><img src="'.$block->getImageUrl($banner->getSlideImage()).'" alt="" /></a>
						</div>' ; 
			echo $html;
			?>
			<?php if($text = $banner->getSlideText()){
				echo $block->getContentText($text);
			}
			?>
			</div>
		<?php } ?>
	</div>
</div>
<script>
	require([
		'jquery',
		'mage/mage',
		'ddv/owl'
	], function ($) {
		'use strict';

		jQuery(".slider_<?php echo $sliderId; ?>").owlCarousel(
			{
				navigationText:['<span></span>','<span></span>'],
				<?php foreach($slider->getSliderSetting() as $key=>$value)
				{
					if(in_array($key, array('autoPlay', 'navigation', 'stopOnHover', 'pagination', 'scrollPerPage'))){
						$value == 0 ? $value = 'false': '';
						$value == 1 ? $value = 'true': '';
					}
					echo $key . ':' . $value . ',';
				} ?>}
		);
	});
</script>
<?php endif; ?>
