<?php

use \Magento\Framework\Stdlib\StringUtils;


	$stringFilter = new \Magento\Framework\Stdlib\StringUtils;
	$enable = $this->getConfig('enable_frontend');
	$auto = $this->getConfig('auto');
	$speed = $this->getConfig('speed');
	$default = $this->getConfig('default');
	$desktop = $this->getConfig('desktop');
	$desktop_small = $this->getConfig('desktop_small');
	$tablet = $this->getConfig('tablet');
	$mobile = $this->getConfig('mobile');
	$pagination = $this->getConfig('pagination');
	$show_next_back = $this->getConfig('show_next_back');
	$show_navigation_control = $this->getConfig('show_navigation_control');
	$title = $this->getConfig('title');
	if($show_next_back)
		$show_next_back = 'true';
	else
		$show_next_back = 'false';
	$show_navigation_control = $this->getConfig('show_navigation_control');
	if($show_navigation_control)
		$show_navigation_control = 'true';
	else
		$show_navigation_control = 'false';
	$_postCollection = $block->getPostCollection();
?>
<?php if ($_postCollection->count() && $enable) { ?>
<div class="box-bottom-home2 box-from-blog">
	<h2><?php echo __($title) ?></h2>
	<div class="from-blog-slider slider-home2">
		<div class="wrap-item">
			<?php foreach ($_postCollection as $_post) { ?>
			<div class="item">
				<div class="wrap-from-blog">
					<div class="from-blog-thumb">
						<a href="<?php echo $_post->getPostUrl() ?>">
							<img alt="" src="<?php echo $this->getMediaFolder().$_post->getThumbnailimage() ?>"/>
						</a>
					</div>
					<div class="from-blog-info">
						<h3><a href="<?php echo $_post->getPostUrl() ?>"><?php echo $block->escapeHtml($_post->getTitle()) ?></a></h3>
						<?php $length = 66; ?>
						<p>
							<?php echo $stringFilter->substr($_post->getShortContent(),0,$length); ?>
						</p>
					</div>
				</div>
				<div class="from-blog-more">
					<ul>
						<?php 
							$date = $_post->getPublishTime();
						?>
						<li><i class="fa fa-calendar-o"></i> <?php echo date("d F Y", strtotime($date)); ?></li>
						<li><i class="fa fa-comment-o"></i> 8</li>
					</ul>
					<a href="<?php echo $_post->getPostUrl() ?>" class="readmore"><i class="fa fa-long-arrow-right"></i></a>
				</div>
			</div>
			<?php } ?>
		</div>
	</div>
	<a href="<?php echo $block->getUrl('blog');?>" class="viewall"><?php echo __('View All');?></a>
</div>

<script type="text/javascript">
	require([
		'jquery',
		'mage/mage',
		'ddv/owl'
	], function ($) {
		'use strict';

		jQuery(".from-blog-slider .wrap-item").owlCarousel({
			items : <?php echo $default; ?>,
			itemsDesktop : [1199,<?php echo $desktop; ?>],
			itemsDesktopSmall : [980,<?php echo $desktop_small; ?>],
			itemsTablet: [768,<?php echo $tablet; ?>],
			itemsMobile : [479,<?php echo $mobile; ?>],
			slideSpeed : <?php echo $pagination; ?>,
			paginationSpeed : <?php echo $pagination; ?>,
			rewindSpeed : <?php echo $pagination; ?>,
			addClassActive: true,
			navigation : <?php echo $show_next_back; ?>,
			stopOnHover : true,
			pagination : <?php echo $show_navigation_control; ?>,
			scrollPerPage:true,
		});
	});
</script>
<?php } ?>